version: "3.9"

services:
  database: #Nome do Service que deve estar no arquivo de criação da conexão
    image: postgres
    container_name: database_ignite
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 #Porta para poder usar o debug
    volumes: 
      - .:/usr/src/app
    links: 
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local