version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    ports: 
      - 5432:5432
    networks:
      - net
    restart: always
    volumes:
      - postgres:/data/postgres

  app:
    build: .
    container_name: server_container
    volumes: 
      - .:/usr/src/app
    links:
      - postgres
    depends_on:
      - postgres
    ports: 
      - 3333:3333
      - 9229:9229
    networks:
      - net
    restart: always

networks:
  net:
    driver: bridge

volumes:
  postgres:
    driver: local